pull_request_rules:
    - name: automatic merge on CI success and review
      conditions:
          - base=master
          - label≠wip
      actions:
          merge:
              method: squash
              strict: smart
              commit_message: title+body
